### ISSUE TITLE
Should we rename Future#recoverWith to flatRecover?

### ISSUE THREAD

**Issue by mlbileschi** [scala/scala#4224]
Hi all,
I've seen personally that people struggle with Twitter's com.twitter.util.Future#handle (AFAICT scala.concurrent.Future#recover) vs com.twitter.util.Future#rescue (analogous to scala.concurrent.Future#recoverWith). I recommended that we internally (in Twitter) switch to the names handle and flatHandle, so that it would be obvious which one flattens, and so that the analogy to map and flatMap was more obvious. It came up that this would possibly be a good place to follow the scala.concurrent.Future naming conventions, but when I saw what the names were, I thought maybe they could use a renaming as well.
1. Am I off base with this analysis?
2. Would you support a renaming?
Thanks!
Max

**Comment by adriaanm** [comment]
Sorry about the lack of response. A lot going on here... Thanks for moving it over to our beloved jira: https://issues.scala-lang.org/browse/SI-9063. These discussions are also welcome over at scala-user/scala-internals.
