### ISSUE TITLE
Scala REPL interprets all line-starting symbols starting with : as REPL commands

### ISSUE THREAD

**Issue by lopopolo** [scala/scala#4392]
```
Welcome to Scala version 2.11.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_05).
Type in expressions to have them evaluated.
Type :help for more information.

scala> 1 :: Nil
res0: List[Int] = List(1)

scala> ::(1, Nil)
:(1,: no such command.  Type :help for help.

scala> :+.unapply(Seq(1,2,3))
+.unapply(Seq(1,2,3)): no such command.  Type :help for help.

scala>  :+.unapply(Seq(1,2,3))
res1: Option[(Seq[Int], Int)] = Some((List(1, 2),3))
```

The last example has a space prefixing the code.

**Comment by som-snytt** [comment]
If this is an issue and not a statement of fact, I'd suggest their Jira https://issues.scala-lang.org/secure/Dashboard.jspa

Maybe ESC should put it into command mode for one line. Feel free to use that suggestion in an issue marked improvement.

**Comment by retronym** [comment]
The space-before-the-identifer trick is the best way to disambiguate for now.
